### ISSUE TITLE
Function output for graph_survs

### ISSUE THREAD

**Issue by BKievit1** [Merck/psm3mkv#16]
@nialldavison and I encountered a minor issue related to the `graph_survs` function.
In addition to documentation issues described previously (see [Issue: Documentation and package name](https://github.com/Merck/psm3mkv/issues/15)). The _psm_ graph output is not correctly displayed, evidence of which can be seen in the example vignette within the `ptdgraphs` object.

<p align="center">
<img src="https://github.com/Merck/psm3mkv/assets/116747843/3aaba5c2-1eed-48e5-89eb-c43ca20caba7" alt="graph_survs_psm_output" width = "450">
</p>
 
Currently, the `draw_2pgraphic` function is not correctly specified to handle the _psm_ input data object `psmdata`. As a result, it does not separate the OS events from the PFS events, resulting in the graph above. The column used for identifying the series (PFS or OS, in this case) is called “Endpoint” whereas the function uses “Method” by default to specify the series.
We suggest either of the following:

- Manually write out the ggplot command for this case:
```R
ggplot2::ggplot(ds, ggplot2::aes(Time, Probability)) +
      ggplot2::geom_line(ggplot2::aes(color = Endpoint)) +
      ggplot2::xlab(“Time from baseline”)
```

- Include a variable for the graph series that is “Method” by default, and can be switched to “Endpoint” for _psm_. For example, `series = "Method"` can be included in the function arguments, then `color = !!rlang::sym(series)` can be added to the body of the function:
```R
  draw_2pgraphic <- function(ds, xlabel="Time from baseline", series = “Method”) {
    Time <- Probability <- Method <- NULL

    ggplot2::ggplot(ds, ggplot2::aes(Time, Probability)) +
      ggplot2::geom_line(ggplot2::aes(color = !!rlang::sym(series))) +
      ggplot2::xlab(xlabel)
  }
```

The call to `draw_2pgraphic` for the _psm_ case would simply include a different series argument, `draw_2pgraphic(psmdata, series = “Endpoint”)`.

**Comment by dom-muston** [comment]
Thank you for trying out this package and raising this issue, @BKievit1 and @nialldavison. I will take a look and aim to fix the function you highlight.

**Comment by dom-muston** [comment]
Thanks again for reviewing the code. Likely graph_survs() is quite inefficient in that it creates different datasets for different endpoints (4 datasets). That said, draw_2pgraphic() is an internal function within graph_survs(), not exposed to any user, and relies on being supplied a dataset specific to an endpoint.

The graphics in the vignette appear to be as intended, and I'm not sure how the graphic above in this Issue was created from externally facing functions from this package.

I'd be grateful for any further information or thoughts you have on this. A more comprehensive rewrite of graph_survs() may be desirable here in due course.

**Comment by dom-muston** [comment]
Hi both, Thanks again for the review. You will see that, in pull request 30, I have reworked the functioning of graph_survs(). Instead of creating 4 temporary datasets, I make create a larger dataset and pivot it wide/long as needed. The draw_2pgraphic() function remains internal within this function. Hopefully this should result in cleaner and more efficient code.
